/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Employee;

import application.entity.Attendance;
import Controller.EmployeeController;
import application.entity.AttendanceId;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import application.forms.Employee.EmployeeView;

/**
 *
 * @author Malinda
 */
public class EmployeeAttendance extends javax.swing.JDialog {

    private EmployeeView employeeView1;
    public DefaultTableModel modelEmployee;
    private EmployeeController employeeController;
    private TableColumnModel tcmEmployee;
    private TableColumn colEmployeeId;
    private TableColumnModel columnModel;

    int count = 0;
    //int searchCount=0;

    /**
     * Creates new form EmployeeAttendance
     */
    public EmployeeAttendance(java.awt.Dialog parent, boolean modal, EmployeeView employeeView1) {

        super(parent, modal);
        initComponents();
        Date date = new Date();
        jDateChooser1.setDate(date);

        setResizable(false);
        setLocationRelativeTo(this);
        this.employeeView1 = employeeView1;

        //checkBtnAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtEmpHours = new javax.swing.JTextField();
        btnMarkAttendance = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAttendance = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        cmbAttendance = new javax.swing.JComboBox<>();
        spnInTimeHour = new javax.swing.JSpinner();
        spnInTimeMnts = new javax.swing.JSpinner();
        spnOutTimeHour = new javax.swing.JSpinner();
        spnOutTimeMnts = new javax.swing.JSpinner();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Attendance");

        jLabel1.setText("Select Date");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Employee Name");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Employee Attendance");

        jLabel5.setText("Employee In Time");

        jLabel6.setText("Employee Out Time");

        jLabel7.setText("Number of Hours Worked");

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        txtEmpHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpHoursActionPerformed(evt);
            }
        });

        btnMarkAttendance.setText("Next Employee");
        btnMarkAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAttendanceActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblViewAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Attendance", "Intime", "OutTime"
            }
        ));
        jScrollPane1.setViewportView(tblViewAttendance);

        jButton1.setText("Check Attendance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbAttendance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Absent", "Present", "Half Day" }));

        spnInTimeHour.setModel(new javax.swing.SpinnerNumberModel(8, 0, 24, 1));

        spnInTimeMnts.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        spnOutTimeHour.setModel(new javax.swing.SpinnerNumberModel(6, 0, 24, 1));

        spnOutTimeMnts.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmpId)
                                    .addComponent(txtEmpName)
                                    .addComponent(cmbAttendance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnInTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(spnInTimeMnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnOutTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spnOutTimeMnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmpHours))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnMarkAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spnInTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnInTimeMnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnOutTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnOutTimeMnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmpHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnMarkAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        //searchCount=1;
        //checkBtnAttendance();
        EmployeeController employeeController = new EmployeeController();
        try {

            List<Attendance> li = employeeController.getEmployeeBById(1);
            Attendance attendance1 = li.get(count);

            txtEmpName.setText(attendance1.getEmployeeName());

            txtEmpId.setText(String.valueOf(attendance1.getAttId().getEmpId()));

        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMarkAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAttendanceActionPerformed
        // TODO add your handling code here:
        EmployeeController employeeController = new EmployeeController();
        try {

            count++;

            List<Attendance> li = employeeController.getEmployeeBById(5);
            if (count == li.size()) {
                JOptionPane.showMessageDialog(rootPane, "All Employee Attendance are Marked");
                //get out
            } else {
                Attendance newAttendance = li.get(count);

                txtEmpName.setText(newAttendance.getEmployeeName());
                txtEmpId.setText(String.valueOf(newAttendance.getAttId().getEmpId()));

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnMarkAttendanceActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        try {
            JOptionPane.showMessageDialog(rootPane, "Employee Name :" + txtEmpName.getText());
            Attendance newAttendance = new Attendance();

            EmployeeController employeeController = new EmployeeController();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dt1;
            dt1 = jDateChooser1.getDate();
            String attDate = (String) sdf.format(jDateChooser1.getDate());

            AttendanceId attendanceId = new AttendanceId(Integer.valueOf(txtEmpId.getText().trim()), attDate);

            newAttendance.setAttId(attendanceId);
            newAttendance.setEmployeeName(txtEmpName.getText().trim());
            newAttendance.setEmployeeAttendance(cmbAttendance.getSelectedItem().toString());

            int timeInH = (int) spnInTimeHour.getValue();
            int timeInM = (int) spnInTimeMnts.getValue();
            int timeOutH = (int) spnOutTimeHour.getValue();
            int timeOutM = (int) spnOutTimeMnts.getValue();

            int InTime = employeeController.InTimeInMinutes(timeInH, timeInM);
            int OutTime = employeeController.OutTimeInMinutes(timeOutH, timeOutM);

            newAttendance.setInTime(String.valueOf(timeInH) + ":" + String.valueOf(timeInM));
            newAttendance.setOutTime(String.valueOf(timeOutH) + ":" + String.valueOf(timeOutM));
            newAttendance.setTimeInMinutes(employeeController.CalcTime(InTime, OutTime));
            int time = OutTime - InTime;
            newAttendance.setNoOfHours(+time / 60 + "." + time % 60);
            newAttendance.setStatus(true);
            newAttendance.setMain(false);

            if (employeeController.save(newAttendance)) {
                JOptionPane.showMessageDialog(this, "Attendance added");

            } else {
                JOptionPane.showMessageDialog(this, "Attendance Not Added");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Already Updated");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DateFormat getDate = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat onlyMonth = new SimpleDateFormat("MM");
        DateFormat onlyDate = new SimpleDateFormat("dd");
        String month = onlyMonth.format(jDateChooser2.getDate());
        String date = onlyDate.format(jDateChooser2.getDate());

        columnModel = tblViewAttendance.getColumnModel();
        modelEmployee = (DefaultTableModel) tblViewAttendance.getModel();
        employeeController = new EmployeeController();
        employeeController.getAllEmployeeAttendance(modelEmployee, Integer.valueOf(date), Integer.valueOf(month));
        tcmEmployee = tblViewAttendance.getColumnModel();
        colEmployeeId = tcmEmployee.getColumn(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmpHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpHoursActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmpHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeAttendance dialog = new EmployeeAttendance(new javax.swing.JDialog(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnMarkAttendance;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbAttendance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnInTimeHour;
    private javax.swing.JSpinner spnInTimeMnts;
    private javax.swing.JSpinner spnOutTimeHour;
    private javax.swing.JSpinner spnOutTimeMnts;
    private javax.swing.JTable tblViewAttendance;
    private javax.swing.JTextField txtEmpHours;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtEmpName;
    // End of variables declaration//GEN-END:variables
/*private void checkBtnAttendance() {
        if (searchCount==1) {
            btnAdd.setEnabled(true);
            btnMarkAttendance.setEnabled(true);
        } else {
            btnAdd.setEnabled(false);
            btnMarkAttendance.setEnabled(false);
        }
    }*/

}
