/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Dashbord;

//import application.forms.Supplier.SupplierView;
import application.entity.Employee;
import application.forms.Advertiser.AdvertiserView;
import application.forms.Customer.CustomerView;
import application.forms.Employee.EmployeeView;
import application.forms.Invoice.InvoiceAdd;
import application.forms.OtherExpense.OtherExpenseView;
import application.forms.Rental.RentalView;

import application.forms.Stock.StockView;
//import application.forms.Stock.stockView;
import application.forms.Supplier.SupplierView;

import java.awt.event.ActionEvent;

import application.forms.Tarnsaport.VehicleView;
import application.forms.Users.UserAdd;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Date;

/**
 *
 * @author Shashiprabha-PC
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    public Dashbord() {
        initComponents();
        setLocationRelativeTo(this);

//      DateTime function        
        getDateAndTime();
        
        LocalDateTime now = LocalDateTime.now();
        int year = now.getYear();
        Month month = now.getMonth();
        int day = now.getDayOfMonth();
        int hour = now.getHour();
        int minute = now.getMinute();
        dayLable.setText(month + "  " + Integer.toString(day) + "," + Integer.toString(year));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        empButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        transportButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        evaluationButton = new javax.swing.JButton();
        payrollButton = new javax.swing.JButton();
        stockButton = new javax.swing.JButton();
        invoiceButton = new javax.swing.JButton();
        invoiceButton1 = new javax.swing.JButton();
        invoiceButton2 = new javax.swing.JButton();
        invoiceButton3 = new javax.swing.JButton();
        timeLable = new javax.swing.JLabel();
        dayLable = new javax.swing.JLabel();
        backgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundPanel.setLayout(null);

        empButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EMPLOYEE.JPG"))); // NOI18N
        empButton.setBorder(null);
        empButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(empButton);
        empButton.setBounds(810, 100, 140, 140);

        customerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer.jpg"))); // NOI18N
        customerButton.setBorder(null);
        customerButton.setPreferredSize(new java.awt.Dimension(140, 140));
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(customerButton);
        customerButton.setBounds(60, 250, 140, 140);

        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.jpg"))); // NOI18N
        supplierButton.setBorder(null);
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(supplierButton);
        supplierButton.setBounds(660, 250, 140, 140);

        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.jpg"))); // NOI18N
        userButton.setBorder(null);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(userButton);
        userButton.setBounds(660, 400, 140, 140);

        transportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transport.jpg"))); // NOI18N
        transportButton.setBorder(null);
        transportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(transportButton);
        transportButton.setBounds(210, 400, 140, 140);

        rentalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rental.jpg"))); // NOI18N
        rentalButton.setBorder(null);
        rentalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentalButtonMouseClicked(evt);
            }
        });
        rentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(rentalButton);
        rentalButton.setBounds(810, 400, 140, 140);

        evaluationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Evaluation.jpg"))); // NOI18N
        evaluationButton.setBorder(null);
        evaluationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(evaluationButton);
        evaluationButton.setBounds(60, 400, 140, 140);

        payrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/advertising.jpg"))); // NOI18N
        payrollButton.setBorder(null);
        payrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(payrollButton);
        payrollButton.setBounds(360, 250, 140, 140);

        stockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stock.jpg"))); // NOI18N
        stockButton.setBorder(null);
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(stockButton);
        stockButton.setBounds(60, 100, 140, 140);

        invoiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-7.jpg"))); // NOI18N
        invoiceButton.setBorder(null);
        backgroundPanel.add(invoiceButton);
        invoiceButton.setBounds(210, 250, 140, 140);

        invoiceButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Invoice.jpg"))); // NOI18N
        invoiceButton1.setBorder(null);
        invoiceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButton1ActionPerformed(evt);
            }
        });
        backgroundPanel.add(invoiceButton1);
        invoiceButton1.setBounds(210, 100, 140, 140);

        invoiceButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-28.jpg"))); // NOI18N
        invoiceButton2.setBorder(null);
        backgroundPanel.add(invoiceButton2);
        invoiceButton2.setBounds(510, 250, 140, 140);

        invoiceButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-3.jpg"))); // NOI18N
        invoiceButton3.setBorder(null);
        backgroundPanel.add(invoiceButton3);
        invoiceButton3.setBounds(810, 250, 140, 140);

        timeLable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeLable.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.add(timeLable);
        timeLable.setBounds(660, 620, 290, 30);

        dayLable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dayLable.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.add(dayLable);
        dayLable.setBounds(660, 580, 290, 30);

        backgroundImageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hadware-dash-back1024x720.png"))); // NOI18N
        backgroundPanel.add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, 0, 1026, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        
        SupplierView supplierView = new SupplierView(null, rootPaneCheckingEnabled);
        supplierView.setVisible(true);
        

    }//GEN-LAST:event_supplierButtonActionPerformed
    

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        CustomerView customerView = new CustomerView(null, rootPaneCheckingEnabled);
        customerView.setVisible(true);
    }//GEN-LAST:event_customerButtonActionPerformed

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButtonActionPerformed
        StockView stockview = new StockView(null, rootPaneCheckingEnabled);
        stockview.setVisible(true);
    }//GEN-LAST:event_stockButtonActionPerformed
    

    private void evaluationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationButtonActionPerformed
        
        OtherExpenseView expenseView = new OtherExpenseView(this, rootPaneCheckingEnabled);
        expenseView.setVisible(true);

    }//GEN-LAST:event_evaluationButtonActionPerformed

    private void rentalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rentalButtonMouseClicked
    private void rentalButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
        RentalView rentalView = new RentalView(null, rootPaneCheckingEnabled);
        rentalView.setVisible(true);
        
    }

    private void transportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportButtonActionPerformed
        VehicleView vehicleView = new VehicleView(null, rootPaneCheckingEnabled);
        vehicleView.setVisible(true);
    }//GEN-LAST:event_transportButtonActionPerformed

    private void invoiceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButton1ActionPerformed
        InvoiceAdd invoiceAdd = new InvoiceAdd(this, rootPaneCheckingEnabled);
        invoiceAdd.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_invoiceButton1ActionPerformed

    private void empButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButtonActionPerformed
        EmployeeView employeeView = new EmployeeView(this, rootPaneCheckingEnabled);
        employeeView.setVisible(true);
    }//GEN-LAST:event_empButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        UserAdd userAdd = new UserAdd(this, rootPaneCheckingEnabled);
        userAdd.setVisible(true);
    }//GEN-LAST:event_userButtonActionPerformed

    private void payrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollButtonActionPerformed
        AdvertiserView advertiserView = new AdvertiserView(this, rootPaneCheckingEnabled);
        advertiserView.setVisible(true);
    }//GEN-LAST:event_payrollButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel dayLable;
    private javax.swing.JButton empButton;
    private javax.swing.JButton evaluationButton;
    private javax.swing.JButton invoiceButton;
    private javax.swing.JButton invoiceButton1;
    private javax.swing.JButton invoiceButton2;
    private javax.swing.JButton invoiceButton3;
    private javax.swing.JButton payrollButton;
    private javax.swing.JButton rentalButton;
    private javax.swing.JButton stockButton;
    private javax.swing.JButton supplierButton;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton transportButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables

    private void getDateAndTime() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String formatedDate = dateFormat.format(date);
//        dateText.setText(formatedDate);

        Thread t1 = new Thread() {
            
            @Override
            public void run() {
                
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss");
                    String FormatedTime = timeFormat.format(date);
                    timeLable.setText(FormatedTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        
                    }
                }
            }
        };
        t1.start();
        
    }
    
}
