/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.OtherExpense;

import Controller.OtherExpensesController;
import application.entity.OtherExpenses;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class OtherExpenseView extends javax.swing.JDialog {

    /**
     * Creates new form OtherExpenseView
     */
    public DefaultTableModel modelOtherExpenses;
    private OtherExpensesController otherExpensesController = null;
    private TableColumnModel tcmOtherExpenses;
    private TableColumn colexpenseId;
    private TableColumnModel columnModel;

    public OtherExpenseView(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
     //   setLocationRelativeTo(parent);

        columnModel = tblOtherExpense.getColumnModel();
        modelOtherExpenses = (DefaultTableModel) tblOtherExpense.getModel();
        otherExpensesController = new OtherExpensesController();
        otherExpensesController.getAllOtherExpenses(modelOtherExpenses);
        tcmOtherExpenses = tblOtherExpense.getColumnModel();
        colexpenseId = tcmOtherExpenses.getColumn(0);
        tcmOtherExpenses.removeColumn(colexpenseId);
        checkBtnOtherExpenses();
        txtOtherExpensesSearch.requestFocus();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOtherExpensesSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOtherExpense = new javax.swing.JTable();
        btnAddOtherExpenses = new javax.swing.JButton();
        btnUpdateOtherExpenses = new javax.swing.JButton();
        btnDeleteOtherExpenses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Other Expenses View");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(953, 611));

        jLabel1.setText("Search");

        txtOtherExpensesSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtherExpensesSearchKeyReleased(evt);
            }
        });

        tblOtherExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Record Id", "Date", "Electricity Bill", "Water Bill", "Insurance", "Rental", "Other", "Total"
            }
        ));
        tblOtherExpense.setPreferredSize(new java.awt.Dimension(452, 402));
        tblOtherExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOtherExpenseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOtherExpense);

        btnAddOtherExpenses.setBackground(new java.awt.Color(255, 255, 255));
        btnAddOtherExpenses.setText("Add");
        btnAddOtherExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOtherExpensesActionPerformed(evt);
            }
        });

        btnUpdateOtherExpenses.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateOtherExpenses.setText("Update");
        btnUpdateOtherExpenses.setPreferredSize(new java.awt.Dimension(51, 23));
        btnUpdateOtherExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOtherExpensesActionPerformed(evt);
            }
        });

        btnDeleteOtherExpenses.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteOtherExpenses.setText("Delete");
        btnDeleteOtherExpenses.setPreferredSize(new java.awt.Dimension(51, 23));
        btnDeleteOtherExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOtherExpensesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdateOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDeleteOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(25, 25, 25)
                                .addComponent(txtOtherExpensesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOtherExpensesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOtherExpensesSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtherExpensesSearchKeyReleased
       final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelOtherExpenses);
        tblOtherExpense.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtOtherExpensesSearch.getText()));
        checkBtnOtherExpenses();
        //        in here "?!" act as "like" operator in sql

    }//GEN-LAST:event_txtOtherExpensesSearchKeyReleased

    private void btnDeleteOtherExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOtherExpensesActionPerformed
       // Delete button action
        int status = JOptionPane.showConfirmDialog(this, "Do you want to delete the other expenses ?", "Delete Other Expenses", JOptionPane.YES_NO_OPTION);
        if (status == JOptionPane.YES_OPTION) {
        int selectedRow = tblOtherExpense.convertRowIndexToModel(tblOtherExpense.getSelectedRow());
            int expenseId = Integer.valueOf(modelOtherExpenses.getValueAt(selectedRow, 0).toString());
            OtherExpenses otherExpenses = otherExpensesController.findOtherExpensesById(expenseId);
            otherExpenses.setStatus(false);
            otherExpenses.setDeletedAt(new Date());
            if (otherExpensesController.update(otherExpenses)) {
                modelOtherExpenses.removeRow(selectedRow);
                checkBtnOtherExpenses();
                JOptionPane.showMessageDialog(this, "Other Expenses deleted successfully.", "Deletion Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error in deleting Other Expenses.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        txtOtherExpensesSearch.requestFocus();
   
    }//GEN-LAST:event_btnDeleteOtherExpensesActionPerformed

    private void btnAddOtherExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOtherExpensesActionPerformed
        OtherExpenseAdd otherExpenseAdd = new OtherExpenseAdd(null, true, this);
        otherExpenseAdd.setVisible(true);
        otherExpensesController.getAllOtherExpenses(modelOtherExpenses);
        checkBtnOtherExpenses();
  
    }//GEN-LAST:event_btnAddOtherExpensesActionPerformed

    private void tblOtherExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOtherExpenseMouseClicked
       checkBtnOtherExpenses();
    }//GEN-LAST:event_tblOtherExpenseMouseClicked

    private void btnUpdateOtherExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOtherExpensesActionPerformed
        //Update button action 
        
        int selectedRow = tblOtherExpense.convertRowIndexToModel(tblOtherExpense.getSelectedRow());
        OtherExpenseUpdate otherExpenseUpdate = new OtherExpenseUpdate(this, true);
        OtherExpenses otherExpenses = new OtherExpenses();
        otherExpenses.setExpenseId(Integer.valueOf(modelOtherExpenses.getValueAt(selectedRow, 0).toString()));
        otherExpenses.setExpenseDate(modelOtherExpenses.getValueAt(selectedRow, 1).toString());
        otherExpenses.setExpenseElectricity(modelOtherExpenses.getValueAt(selectedRow, 2).toString());
        otherExpenses.setExpenseWater(modelOtherExpenses.getValueAt(selectedRow, 3).toString());
        otherExpenses.setExpenseInsurance(modelOtherExpenses.getValueAt(selectedRow, 4).toString());
        otherExpenses.setExpenseRental(modelOtherExpenses.getValueAt(selectedRow, 5).toString());
        otherExpenses.setExpenseOther(modelOtherExpenses.getValueAt(selectedRow, 6).toString());
        otherExpenses.setExpenseTotal(modelOtherExpenses.getValueAt(selectedRow, 7).toString());
        otherExpenseUpdate.setOtherExpensesUpdate(otherExpenses);
        otherExpenseUpdate.setVisible(true);
        otherExpensesController.getAllOtherExpenses(modelOtherExpenses);
        checkBtnOtherExpenses();
        txtOtherExpensesSearch.requestFocus();

    }//GEN-LAST:event_btnUpdateOtherExpensesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OtherExpenseView dialog = new OtherExpenseView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOtherExpenses;
    private javax.swing.JButton btnDeleteOtherExpenses;
    private javax.swing.JButton btnUpdateOtherExpenses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOtherExpense;
    private javax.swing.JTextField txtOtherExpensesSearch;
    // End of variables declaration//GEN-END:variables
 private void checkBtnOtherExpenses() {
        if (tblOtherExpense.getSelectedRowCount() > 0) {
            btnDeleteOtherExpenses.setEnabled(true);
            btnUpdateOtherExpenses.setEnabled(true);
        } else {
            btnDeleteOtherExpenses.setEnabled(false);
            btnUpdateOtherExpenses.setEnabled(false);
        }
    }
   
}
