/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Login;

import application.forms.Dashbord.Dashbord;
import hardwaremanagement.HibernateUtil;
import hardwaremanagement.HardwareManagement;
import Controller.DbCommon;
import application.entity.Users;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;


/**
 *
 * @author Shashiprabha-PC
 */
public class Login extends javax.swing.JFrame {
    HibernateUtil hibernateUtil;
    
    public HibernateUtil getHibernateUtil() {
        return hibernateUtil;
    }
        
         

    /**
     * Creates new form Login
     */
    public Login()  {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        loginLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(979, 680));
        setResizable(false);

        jPanel1.setLayout(null);

        txtUserName.setBackground(new java.awt.Color(215, 215, 215));
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName);
        txtUserName.setBounds(420, 310, 200, 35);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login-button290x40.png"))); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(350, 430, 290, 40);

        txtPassword.setBackground(new java.awt.Color(215, 215, 215));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(420, 360, 200, 30);

        loginLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-fnl.jpg"))); // NOI18N
        jPanel1.add(loginLable);
        loginLable.setBounds(0, 0, 1000, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        List list = null;
        Session session =null;
        Query query = null;
        
        try{
            Dashbord dashbord = new Dashbord();
            dashbord.setVisible(true);/*
            JOptionPane.showMessageDialog(null, "Welcome ");
            session=hibernateUtil.openReadableDbConnection();
            JOptionPane.showMessageDialog(null, "Welcome 123");
            query=session.createQuery("FROM Users");
            query.setParameter("userName", txtUserName.getText());
            query.setParameter("userPassword", txtPassword.getText());
            //System.out.println(list=query.list());
            JOptionPane.showMessageDialog(null, "Welcome ");
            // JOptionPane.showMessageDialog(null,"No data ");
            
            String sql="select * from users_list";
          session.createSQLQuery(sql).executeUpdate();
            
            
            
            Configuration cfg= new Configuration();
            cfg.configure("hibernate.cfg.xml");
            SessionFactory factory = cfg.buildSessionFactory();
            session = factory.openSession();
           
            JOptionPane.showMessageDialog(null, "Welcome 123");
            query=session.createQuery("from Users");
            list = query.list();
            JOptionPane.showMessageDialog(null, "Welcome 123"+list);
           
            
           
            if (list.isEmpty()){
                JOptionPane.showMessageDialog(null,"No data ");
                Dashbord dashbord = new Dashbord();
                dashbord.setVisible(true);
            }       
            /*else{
                JOptionPane.showMessageDialog(null, "Welcome "+txtUserName.getText());
            }*/
        }
        catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Something wrong "+ex);
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLable;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
