/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Advertiser;
import Controller.AdvertiserController;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Malinda
 */
public class AdvertiserView extends javax.swing.JDialog {
    
    public DefaultTableModel modelEmployee;
    private AdvertiserController advertiserController;
    private TableColumnModel tcmEmployee;
    private TableColumn colEmployeeId;
    private TableColumnModel columnModel;

    /**
     * Creates new form AdvertiserView
     */
    public AdvertiserView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        tbTypes = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPoster = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTvChannel = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOnline = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNewsPaper = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Advertiser View");
        setPreferredSize(new java.awt.Dimension(953, 611));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tbTypes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        tblPoster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact Number", "Size", "Cost Per Month"
            }
        ));
        jScrollPane5.setViewportView(tblPoster);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTypes.addTab("Poster", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Size", "Number of adds per day", "Length of an add", "Cost Per Month", "Contact Number"
            }
        ));
        jScrollPane4.setViewportView(tblDisplay);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTypes.addTab("Display", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        tbTypes.addTab("Radio", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        tbTypes.addTab("Sponsorships", jPanel6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblTvChannel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channel Name", "Cost Per Day", "Number of Adds Per Day", "Contact Number"
            }
        ));
        jScrollPane1.setViewportView(tblTvChannel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTypes.addTab("TV Channel", jPanel1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tblOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Website", "Number of Adds Per Day", "Cost Per Month", "Contact Number"
            }
        ));
        jScrollPane3.setViewportView(tblOnline);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTypes.addTab("Online", jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblNewsPaper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NewsPaper Name", "Size", "Contact Number", "Cost Per Day"
            }
        ));
        jScrollPane2.setViewportView(tblNewsPaper);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTypes.addTab("NewsPaper", jPanel2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "News Paper", "TV Channel", "Poster", "Display", "Online", "Radio", "Event Sponsorship" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Catergory");

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbTypes)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdd)))
                        .addGap(25, 25, 25))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addComponent(tbTypes)
                .addGap(14, 14, 14)
                .addComponent(btnAdd)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdvertiserController advertiserController=new AdvertiserController();
        //advertiserController.getAllAdvertisers(cmbType.getSelectedItem().toString());
        
        if(cmbType.getSelectedItem().toString().equals("TV Channel")){
            tbTypes.setSelectedIndex(5);
            columnModel = tblTvChannel.getColumnModel();
            modelEmployee = (DefaultTableModel) tblTvChannel.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblTvChannel.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("News Paper"))
        {
            tbTypes.setSelectedIndex(0);
            columnModel = tblNewsPaper.getColumnModel();
            modelEmployee = (DefaultTableModel) tblNewsPaper.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblNewsPaper.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        
        
            
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Online")){
            tbTypes.setSelectedIndex(6);
            columnModel = tblOnline.getColumnModel();
            modelEmployee = (DefaultTableModel) tblOnline.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblOnline.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Display")){
            tbTypes.setSelectedIndex(2);
            columnModel = tblDisplay.getColumnModel();
            modelEmployee = (DefaultTableModel) tblDisplay.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblDisplay.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Poster")){
            tbTypes.setSelectedIndex(1);
            columnModel = tblPoster.getColumnModel();
            modelEmployee = (DefaultTableModel) tblPoster.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblPoster.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
        AdvertiserController advertiserController=new AdvertiserController();
        //advertiserController.getAllAdvertisers(cmbType.getSelectedItem().toString());
        
        if(cmbType.getSelectedItem().toString().equals("TV Channel")){
            tbTypes.setSelectedIndex(5);
            columnModel = tblTvChannel.getColumnModel();
            modelEmployee = (DefaultTableModel) tblTvChannel.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblTvChannel.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("News Paper"))
        {
            tbTypes.setSelectedIndex(0);
            columnModel = tblNewsPaper.getColumnModel();
            modelEmployee = (DefaultTableModel) tblNewsPaper.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblNewsPaper.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        
        
            
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Online")){
            tbTypes.setSelectedIndex(6);
            columnModel = tblOnline.getColumnModel();
            modelEmployee = (DefaultTableModel) tblOnline.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblOnline.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Display")){
            tbTypes.setSelectedIndex(2);
            columnModel = tblDisplay.getColumnModel();
            modelEmployee = (DefaultTableModel) tblDisplay.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblDisplay.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        
        
        }
        else if (cmbType.getSelectedItem().toString().toString().equals("Poster")){
            tbTypes.setSelectedIndex(1);
            columnModel = tblPoster.getColumnModel();
            modelEmployee = (DefaultTableModel) tblPoster.getModel();
            advertiserController = new AdvertiserController();
            advertiserController.getAllAdvertisers(modelEmployee, cmbType.getSelectedItem().toString());
            tcmEmployee = tblPoster.getColumnModel();
            colEmployeeId = tcmEmployee.getColumn(0);
        }
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AdvertiserAdd advertiserAdd = new AdvertiserAdd(this, true, this);
        advertiserAdd.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertiserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertiserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertiserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertiserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdvertiserView dialog = new AdvertiserView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane tbTypes;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTable tblNewsPaper;
    private javax.swing.JTable tblOnline;
    private javax.swing.JTable tblPoster;
    private javax.swing.JTable tblTvChannel;
    // End of variables declaration//GEN-END:variables
}
