/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Advertiser;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Controller.AdvertiserController;
import application.entity.AdvertisersNewsPaper;
import application.entity.Advertiser;
import application.entity.AdvertisersDisplays;
import application.entity.AdvertisersOnline;
import application.entity.AdvertisersPoster;
import application.entity.AdvertisersTvChannel;
import java.util.Date;

/**
 *
 * @author Malinda
 */
public class AdvertiserAdd extends javax.swing.JDialog {

    /**
     * Creates new form AdvertiserAdd
     */
    public AdvertiserAdd(java.awt.Dialog parent, boolean modal, AdvertiserView advertiserView) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tbTypes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlTvChannel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTVChannelName = new javax.swing.JTextField();
        txtTVCost = new javax.swing.JTextField();
        txtTVContact = new javax.swing.JTextField();
        txtTVtimes = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlNewsPaper = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddName = new javax.swing.JTextField();
        txtAddSize = new javax.swing.JTextField();
        txtAddContact = new javax.swing.JTextField();
        txtAddCost = new javax.swing.JTextField();
        pnlPoster = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPOSTERName = new javax.swing.JTextField();
        txtPOSTERContact = new javax.swing.JTextField();
        txtPOSTERSize = new javax.swing.JTextField();
        txtPOSTERCost = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDISPLAYName = new javax.swing.JTextField();
        txtDISPLAYSize = new javax.swing.JTextField();
        txtDISPLAYTimes = new javax.swing.JTextField();
        txtDISPLAYLength = new javax.swing.JTextField();
        txtDISPLAYCost = new javax.swing.JTextField();
        txtDISPLAYContact = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtONLINEName = new javax.swing.JTextField();
        txtONLINETimes = new javax.swing.JTextField();
        txtONLINECost = new javax.swing.JTextField();
        txtONLINEContact = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Sponsorships = new javax.swing.JPanel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Advertiser Add");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbTypes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlTvChannel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Channel Name");

        jLabel3.setText("Cost Per day");

        jLabel4.setText("Contact Number");

        txtTVChannelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTVChannelNameActionPerformed(evt);
            }
        });

        txtTVCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTVCostActionPerformed(evt);
            }
        });

        jLabel22.setText("Number of adds per day");

        javax.swing.GroupLayout pnlTvChannelLayout = new javax.swing.GroupLayout(pnlTvChannel);
        pnlTvChannel.setLayout(pnlTvChannelLayout);
        pnlTvChannelLayout.setHorizontalGroup(
            pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTvChannelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTVContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txtTVCost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTVChannelName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTVtimes))
                .addContainerGap(507, Short.MAX_VALUE))
        );
        pnlTvChannelLayout.setVerticalGroup(
            pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTvChannelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTVChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTVCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTVContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlTvChannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTVtimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTvChannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTvChannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbTypes.addTab("TV Channel", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlNewsPaper.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("NewsPaper Name");

        jLabel6.setText("Size of an advertisement");

        jLabel7.setText("Contact Number");

        jLabel8.setText("Cost Per Day");

        txtAddCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewsPaperLayout = new javax.swing.GroupLayout(pnlNewsPaper);
        pnlNewsPaper.setLayout(pnlNewsPaperLayout);
        pnlNewsPaperLayout.setHorizontalGroup(
            pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewsPaperLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(100, 100, 100)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAddContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(txtAddSize, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddCost))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        pnlNewsPaperLayout.setVerticalGroup(
            pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewsPaperLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlNewsPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAddCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewsPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewsPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbTypes.addTab("NewsPaper", jPanel2);

        pnlPoster.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Name of the Person");

        jLabel10.setText("Contact Number");

        jLabel11.setText("Size of the Frame");

        jLabel12.setText("Cost Per Month");

        javax.swing.GroupLayout pnlPosterLayout = new javax.swing.GroupLayout(pnlPoster);
        pnlPoster.setLayout(pnlPosterLayout);
        pnlPosterLayout.setHorizontalGroup(
            pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPosterLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(100, 100, 100)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPOSTERSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txtPOSTERContact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPOSTERName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPOSTERCost))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        pnlPosterLayout.setVerticalGroup(
            pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPosterLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPOSTERName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPOSTERContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPOSTERSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPOSTERCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        tbTypes.addTab("Poster", pnlPoster);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Name of the Person");

        jLabel14.setText("Size of the Display");

        jLabel15.setText("Number Of advertisemnts per day");

        jLabel16.setText("Length Of An Advertisement");

        jLabel17.setText("Cost Per Month");

        jLabel23.setText("Contact Number");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDISPLAYCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(txtDISPLAYLength, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDISPLAYTimes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDISPLAYSize, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDISPLAYName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDISPLAYContact))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDISPLAYName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDISPLAYSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDISPLAYTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDISPLAYLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtDISPLAYCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDISPLAYContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbTypes.addTab("Displays", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Name of The Website");

        jLabel19.setText("Number OF Times Advertisement shown per day");

        jLabel20.setText("Cost Per Month");

        jLabel21.setText("Contact Number");

        txtONLINEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtONLINENameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtONLINECost, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                            .addComponent(txtONLINEContact, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(191, 191, 191)
                        .addComponent(txtONLINEName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(63, 63, 63)
                        .addComponent(txtONLINETimes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtONLINEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtONLINETimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtONLINECost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtONLINEContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        tbTypes.addTab("Online", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        tbTypes.addTab("Radio", jPanel6);

        Sponsorships.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SponsorshipsLayout = new javax.swing.GroupLayout(Sponsorships);
        Sponsorships.setLayout(SponsorshipsLayout);
        SponsorshipsLayout.setHorizontalGroup(
            SponsorshipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        SponsorshipsLayout.setVerticalGroup(
            SponsorshipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        tbTypes.addTab("Sponsorships", Sponsorships);

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "News Paper", "TV Channel", "Poster", "Display", "Online", "Radio", "Event Sponsorship" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Advertiser Catrgory");

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tbTypes))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(tbTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnAdd)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
        if (cmbType.getSelectedItem().toString().equals("News Paper")) {
            pnlTvChannel.setVisible(true);
            tbTypes.setSelectedIndex(1);
        } else if (cmbType.getSelectedItem().toString().toString().equals("TV Channel")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(0);
        } else if (cmbType.getSelectedItem().toString().toString().equals("Poster")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(2);
        } else if (cmbType.getSelectedItem().toString().toString().equals("Display")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(3);
        } else if (cmbType.getSelectedItem().toString().toString().equals("Online")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(4);
        } else if (cmbType.getSelectedItem().toString().toString().equals("Radio")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(5);
        } else if (cmbType.getSelectedItem().toString().toString().equals("Event Sponsorship")) {
            pnlNewsPaper.setVisible(true);
            tbTypes.setSelectedIndex(6);
        }

    }//GEN-LAST:event_cmbTypeActionPerformed

    private void txtTVChannelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTVChannelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTVChannelNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        switch (cmbType.getSelectedItem().toString()) {
            case "News Paper":
                try {
                    AdvertiserController advertiserController = new AdvertiserController();
                    AdvertisersNewsPaper adNewsPaper = new AdvertisersNewsPaper();
                    Advertiser advertiser = new Advertiser();
                    advertiser.setType("NewsPaper");
                    advertiser.setStatus(true);

                    adNewsPaper.setAdvertiser(advertiser);
                    adNewsPaper.setContactNumber(txtAddContact.getText().trim());
                    adNewsPaper.setCost(Float.valueOf(txtAddCost.getText().trim()));
                    adNewsPaper.setNewsPaperName(txtAddName.getText().trim());
                    adNewsPaper.setSize(Float.valueOf(txtAddSize.getText().trim()));
                    adNewsPaper.setCreatedAt(new Date());
                    adNewsPaper.setUpdatedAt(new Date());
                    adNewsPaper.setStatus(true);
                    advertiserController.save(advertiser);
                    if (advertiserController.save(adNewsPaper)) {
                        JOptionPane.showMessageDialog(this, "News Paper added successfully. ", "Success Message", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error in News Paper adding.", "Error Message", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error Message" + ex);
                }
                break;
            case "TV Channel":
                try {
                    AdvertiserController advertiserController = new AdvertiserController();
                    AdvertisersTvChannel adTvChannel = new AdvertisersTvChannel();
                    Advertiser advertiser = new Advertiser();
                    advertiser.setType("TV Channel");
                    advertiser.setStatus(true);

                    adTvChannel.setAdvertiser(advertiser);
                    adTvChannel.setChannelName(txtTVChannelName.getText().trim());
                    adTvChannel.setContactNumber(txtTVContact.getText().trim());
                    adTvChannel.setCostPerDay(Float.valueOf(txtTVCost.getText().trim()));
                    adTvChannel.setFrequency(Integer.valueOf(txtTVtimes.getText().trim()));
                    adTvChannel.setCreatedAt(new Date());
                    adTvChannel.setUpdatedAt(new Date());
                    adTvChannel.setStatus(true);

                    advertiserController.save(advertiser);
                    if (advertiserController.save(adTvChannel)) {
                        JOptionPane.showMessageDialog(this, "TV Channel added successfully. ", "Success Message", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error in TV Channel adding.", "Error Message", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error Message" + ex);
                }
                break;
            case "Poster":
                try {
                    AdvertiserController advertiserController = new AdvertiserController();
                    AdvertisersPoster adPoster = new AdvertisersPoster();
                    Advertiser advertiser = new Advertiser();
                    advertiser.setType("Poster");
                    advertiser.setStatus(true);

                    adPoster.setAdvertiser(advertiser);
                    adPoster.setName(txtPOSTERName.getText().trim());
                    adPoster.setContactNumber(txtPOSTERContact.getText().trim());
                    adPoster.setCost(Float.valueOf(txtPOSTERCost.getText().trim()));
                    adPoster.setSize(Float.valueOf(txtPOSTERSize.getText().trim()));
                    adPoster.setCreatedAt(new Date());
                    adPoster.setUpdatedAt(new Date());
                    adPoster.setStatus(true);

                    advertiserController.save(advertiser);
                    if (advertiserController.save(adPoster)) {
                        JOptionPane.showMessageDialog(this, "Poster added successfully. ", "Success Message", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error in Poster adding.", "Error Message", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error Message" + ex);
                }
                break;
            case "Display":
                try {
                    AdvertiserController advertiserController = new AdvertiserController();
                    AdvertisersDisplays adDisplays = new AdvertisersDisplays();
                    Advertiser advertiser = new Advertiser();
                    advertiser.setType("Display");
                    advertiser.setStatus(true);

                    adDisplays.setAdvertiser(advertiser);
                    adDisplays.setName(txtDISPLAYName.getText().trim());
                    adDisplays.setContactNumber(txtDISPLAYContact.getText().trim());
                    adDisplays.setCost(Float.valueOf(txtDISPLAYCost.getText().trim()));
                    adDisplays.setSize(Float.valueOf(txtDISPLAYSize.getText().trim()));
                    adDisplays.setTimes(Integer.valueOf(txtDISPLAYTimes.getText().trim()));
                    adDisplays.setDuration(Float.valueOf(txtDISPLAYLength.getText().trim()));
                    adDisplays.setCreatedAt(new Date());
                    adDisplays.setUpdatedAt(new Date());
                    adDisplays.setStatus(true);
                    advertiserController.save(advertiser);
                    if (advertiserController.save(adDisplays)) {
                        JOptionPane.showMessageDialog(this, "Display added successfully. ", "Success Message", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error in Display adding.", "Error Message", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error Message" + ex);
                }
                break;
            case "Online":
                try {
                    AdvertiserController advertiserController = new AdvertiserController();
                    AdvertisersOnline adOnline = new AdvertisersOnline();
                    Advertiser advertiser = new Advertiser();
                    advertiser.setType("Online");
                    advertiser.setStatus(true);

                    adOnline.setAdvertiser(advertiser);
                    adOnline.setWebsite(txtONLINEName.getText().trim());
                    adOnline.setContactNumber(txtONLINEContact.getText().trim());
                    adOnline.setCost(Float.valueOf(txtONLINECost.getText().trim()));
                    adOnline.setTimes(Float.valueOf(txtONLINETimes.getText().trim()));
                    adOnline.setCreatedAt(new Date());
                    adOnline.setUpdatedAt(new Date());
                    adOnline.setStatus(true);

                    advertiserController.save(advertiser);
                    if (advertiserController.save(adOnline)) {
                        JOptionPane.showMessageDialog(this, "Online added successfully. ", "Success Message", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error in Online adding.", "Error Message", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error Message" + ex);
                }
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAddCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddCostActionPerformed

    private void txtTVCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTVCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTVCostActionPerformed

    private void txtONLINENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtONLINENameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtONLINENameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertiserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertiserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertiserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertiserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdvertiserAdd dialog = new AdvertiserAdd(new javax.swing.JDialog(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sponsorships;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlNewsPaper;
    private javax.swing.JPanel pnlPoster;
    private javax.swing.JPanel pnlTvChannel;
    private javax.swing.JTabbedPane tbTypes;
    private javax.swing.JTextField txtAddContact;
    private javax.swing.JTextField txtAddCost;
    private javax.swing.JTextField txtAddName;
    private javax.swing.JTextField txtAddSize;
    private javax.swing.JTextField txtDISPLAYContact;
    private javax.swing.JTextField txtDISPLAYCost;
    private javax.swing.JTextField txtDISPLAYLength;
    private javax.swing.JTextField txtDISPLAYName;
    private javax.swing.JTextField txtDISPLAYSize;
    private javax.swing.JTextField txtDISPLAYTimes;
    private javax.swing.JTextField txtONLINEContact;
    private javax.swing.JTextField txtONLINECost;
    private javax.swing.JTextField txtONLINEName;
    private javax.swing.JTextField txtONLINETimes;
    private javax.swing.JTextField txtPOSTERContact;
    private javax.swing.JTextField txtPOSTERCost;
    private javax.swing.JTextField txtPOSTERName;
    private javax.swing.JTextField txtPOSTERSize;
    private javax.swing.JTextField txtTVChannelName;
    private javax.swing.JTextField txtTVContact;
    private javax.swing.JTextField txtTVCost;
    private javax.swing.JTextField txtTVtimes;
    // End of variables declaration//GEN-END:variables
}
