/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.Tarnsaport;

import Controller.TransportController;
import application.entity.Customer;
import application.entity.Transport;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class VehicleView extends javax.swing.JDialog {
    
     public DefaultTableModel modelVehicle;
     private TransportController transportController = null;
     private TableColumnModel tcmTransport;
     private TableColumn colVehicleId;
     private TableColumnModel columnModel;

    /**
     * Creates new form TansportView
     */
    public VehicleView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        columnModel = tblVehicle.getColumnModel();
        modelVehicle = (DefaultTableModel) tblVehicle.getModel();
        transportController = new TransportController();
        transportController.getAllVehicle(modelVehicle);
        tcmTransport = tblVehicle.getColumnModel();
        colVehicleId = tcmTransport.getColumn(0);
        tcmTransport.removeColumn(colVehicleId);
        checkBtnVehicle();
        txtVehicleSearch.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAddVehicle = new javax.swing.JButton();
        btnUpdateVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        txtVehicleSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicale View");
        setPreferredSize(new java.awt.Dimension(953, 611));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("search");

        btnAddVehicle.setBackground(new java.awt.Color(255, 255, 255));
        btnAddVehicle.setText("Add");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnUpdateVehicle.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateVehicle.setText("update");
        btnUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteVehicle.setText("Delete");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        txtVehicleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleSearchActionPerformed(evt);
            }
        });
        txtVehicleSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleSearchKeyReleased(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration No", "Brand", "Model", "Type"
            }
        ));
        jScrollPane2.setViewportView(tblVehicle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVehicleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtVehicleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        VehicleAdd vehicleAdd = new VehicleAdd(this,true,this);
        vehicleAdd.setVisible(true);
        transportController.getAllVehicle(modelVehicle);
        checkBtnVehicle();

    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVehicleActionPerformed

        int selectedRow = tblVehicle.convertRowIndexToModel(tblVehicle.getSelectedRow());
        //        when we are going to normaly update the table row below way is ok, we can take the table model of supplier
        //fill up the table model with row value and column value then passing to supplier update form "setsupplierupdate"
        // in update form will get the value form supplier view and set value to update form text boxes.

        //usage of "converRwIndexModel is if we upadte after serching we need to take the model of table

        VehicleUpdate vehicleUpdate = new VehicleUpdate(this,true);
        Transport transport = new Transport();
        transport.setVehicleId(Integer.valueOf(modelVehicle.getValueAt(selectedRow, 0).toString()));
        transport.setvNumber(modelVehicle.getValueAt(selectedRow, 1).toString());
        transport.setModel(modelVehicle.getValueAt(selectedRow, 2).toString());
        transport.setType(modelVehicle.getValueAt(selectedRow, 3).toString());

        vehicleUpdate.setVehicleUpdate(transport);
        vehicleUpdate.setVisible(true);
        transportController.getAllVehicle(modelVehicle);
        checkBtnVehicle();
        txtVehicleSearch.requestFocus();
    }//GEN-LAST:event_btnUpdateVehicleActionPerformed

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed

        int status = JOptionPane.showConfirmDialog(this, "Do you want to delete this Vehicle ?", "Delete Vehicle", JOptionPane.YES_NO_OPTION);
        if (status == JOptionPane.YES_OPTION) {
            int selectedRow = tblVehicle.convertRowIndexToModel(tblVehicle.getSelectedRow());
            int vehicleId = Integer.valueOf(modelVehicle.getValueAt(selectedRow, 0).toString());
            Transport transport = transportController.findVehicleId(vehicleId);
            transport.setStatus(false);

            if (transportController.update(transport)) {
                modelVehicle.removeRow(selectedRow);
                checkBtnVehicle();
                JOptionPane.showMessageDialog(this, "Vehicle deleted successfully.", "Deletion Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error in Vehicle deleting.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        txtVehicleSearch.requestFocus();
    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void txtVehicleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleSearchActionPerformed

    private void txtVehicleSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleSearchKeyReleased
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelVehicle);
        tblVehicle.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtVehicleSearch.getText()));
        checkBtnVehicle();
        //        in here "?!" act as "like" operator in sql
    }//GEN-LAST:event_txtVehicleSearchKeyReleased
    private void tblVehicleMouseClicked(java.awt.event.MouseEvent evt) {                                         
        checkBtnVehicle();
                
    }   
    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VehicleView dialog = new VehicleView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void checkBtnVehicle() {
        if (tblVehicle.getSelectedRowCount() > 0) {
            btnDeleteVehicle.setEnabled(true);
            btnUpdateVehicle.setEnabled(true);
        } else {
            btnDeleteVehicle.setEnabled(false);
            btnUpdateVehicle.setEnabled(false);
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTextField txtVehicleSearch;
    // End of variables declaration//GEN-END:variables
}
